/** Emit the generated Aiken fixture modules in `aiken fmt` style. */
import { committeeCommitment, required } from "./commitment";
import { dummyLeafHash, keypairs, keysetRoot, scenarios } from "./fixtures";
import { keccak } from "./keccak";
import { Mmr } from "./mmr";
import { buildMultiproof, type ProofNode } from "./multiproof";
import { encodeCommitment, encodeLeaf, u32le, type MmrLeaf } from "./scale";
import { byKey, keypair, sign } from "./sign";
import { hex } from "./update";

const bytes = (b: Uint8Array): string => `#"${hex(b)}"`;

const list = (items: readonly string[], indent: string): string =>
  items.length === 0
    ? "[]"
    : `[\n${items.map((i) => `${indent}  ${i},`).join("\n")}\n${indent}]`;

const constant = (name: string, value: string): string =>
  `pub const ${name} =\n  ${value}\n`;

/** `lib/bridge/vectors.ak`: keys, keyset root, the six scenarios, the MIP MMR vector. */
export function vectorsAk(): string {
  const three = new Mmr(Array.from({ length: 7 }, (_, i) => dummyLeafHash(i)));
  const out: string[] = [
    "//// Generated by `bun tests/bridge/generate.ts` from `tests/bridge/reference/`.",
    "//// Do not edit by hand. The MIP §Test vectors committee (seats `(1, 2, 1)`),",
    "//// signed scenarios over MMRs whose last leaf names `next_id`, and the",
    "//// three-peak MMR vector (leaf 5 of 7).",
    "",
    "/// A signed commitment over an MMR whose last leaf names `next_id`; `sigs` are in key order.",
    "pub type Scenario {",
    "  set_id: Int,",
    "  block_number: Int,",
    "  next_id: Int,",
    "  parent_hash: ByteArray,",
    "  mmr_root: ByteArray,",
    "  sigs: List<ByteArray>,",
    "}",
    "",
    constant(
      "keys",
      list(
        keypairs.map((kp) => bytes(kp.public)),
        "  ",
      ),
    ),
    constant("keyset_root", bytes(keysetRoot)),
  ];
  for (const s of scenarios) {
    out.push(
      `pub const ${s.name} =\n  Scenario {\n    set_id: ${s.setId},\n    block_number: ${s.blockNumber},\n    next_id: ${s.nextId},\n    parent_hash: ${bytes(s.parentHash)},\n    mmr_root: ${bytes(s.mmrRoot)},\n    sigs: ${list(s.sigs.map(bytes), "    ")},\n  }\n`,
    );
  }
  out.push(
    "// MIP §Test vectors, three peaks: leaf 5 of 7 under the middle peak.",
    "",
    constant("three_peaks_leaf_hash", bytes(three.leafHashes[5])),
    constant("three_peaks_items", list(three.proof(5).map(bytes), "  ")),
    constant("three_peaks_root", bytes(three.root())),
  );
  return out.join("\n");
}

// Signer cap: committees of N single-seat keys, quorum with abstentions every
// third key, one MMR proof of depth 20. Mirrors `lib/bridge/signer_cap.ak`.

const DEPTH = 20;
const BLOCK = 1 << DEPTH;
const SET_ID = 4n;
const NEXT_ID = 5n;

/** Proof for the last leaf of a full tree of `BLOCK` leaves, without materialising the MMR class. */
function lastLeafProof(lastHash: Uint8Array): {
  root: Uint8Array;
  items: Uint8Array[];
} {
  let layer: Uint8Array[] = Array.from({ length: BLOCK }, (_, i) =>
    i === BLOCK - 1 ? lastHash : dummyLeafHash(i),
  );
  const items: Uint8Array[] = [];
  while (layer.length > 1) {
    items.push(layer[layer.length - 2]);
    const next: Uint8Array[] = new Array(layer.length / 2);
    for (let i = 0; i < layer.length; i += 2)
      next[i / 2] = keccak(new Uint8Array([...layer[i], ...layer[i + 1]]));
    layer = next;
  }
  return { root: layer[0], items };
}

const proofExpr = (node: ProofNode): string =>
  Array.isArray(node)
    ? `builtin.list_data([${node.map(proofExpr).join(", ")}])`
    : `builtin.b_data(${bytes(node)})`;

export function signerCapAk(
  sizes: readonly number[] = [50, 100, 150, 170, 200],
): string {
  const out = [
    "//// Generated by `bun tests/bridge/generate.ts --signer-cap`: committees of N",
    "//// single-seat keys, quorum signatures with abstentions spread every third",
    `//// key, one MMR proof of depth ${DEPTH} (block ${BLOCK}). Do not edit by hand.`,
    "",
    "use aiken/builtin",
    "use bridge/signer_cap.{Cap}",
    "",
  ];
  for (const n of sizes) {
    const keyed = Array.from({ length: n }, (_, i) =>
      keypair(1000n + BigInt(i)),
    ).sort(byKey);
    const { commitment, leaves } = committeeCommitment(
      SET_ID,
      keyed.map((kp) => ({ key: kp.public, seats: 1 })),
    );
    const need = required(n, 2, 3);
    const signer = keyed.map((_, i) => i % 3 !== 2);
    for (let i = n - 1; signer.filter(Boolean).length < need; i--)
      signer[i] = true;
    const parentHash = keccak(
      new Uint8Array([
        ...new TextEncoder().encode("parent"),
        ...u32le(BLOCK),
        ...u32le(n),
      ]),
    );
    const leaf: MmrLeaf = {
      parentNumber: BLOCK - 1,
      parentHash,
      nextAuthoritySet: {
        validatorSetId: NEXT_ID,
        seatCount: n,
        keysetCommitment: commitment.keysetCommitment,
      },
    };
    const { root, items } = lastLeafProof(keccak(encodeLeaf(leaf)));
    const msg = keccak(encodeCommitment(root, BLOCK, SET_ID));
    const sigs = keyed.flatMap((kp, i) => (signer[i] ? [sign(kp, msg)] : []));
    const signers = new Set(signer.flatMap((s, i) => (s ? [i] : [])));
    out.push(
      `pub const cap_${n} =\n  Cap {\n    seat_count: ${n},\n    signatures: ${list(sigs.map(bytes), "    ")},\n    multiproof: ${proofExpr(buildMultiproof(leaves, signers))},\n    keyset_root: ${bytes(commitment.keysetCommitment)},\n    parent_hash: ${bytes(parentHash)},\n    mmr_root: ${bytes(root)},\n    mmr_proof: ${list(items.map(bytes), "    ")},\n  }\n`,
    );
  }
  return out.join("\n");
}
