name = "midnight/reserve"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'midnight/reserve'"

[repository]
user = "midnight"
project = "reserve"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config.default]
cnight_policy = "thing_cool"
reserve_one_shot_hash = "yes_no_test"
reserve_one_shot_index = 1
reserve_two_stage_hash = "blah_blah"
reserve_forever_hash = "forever_hash"
council_one_shot_hash = "yes_no_test"
council_one_shot_index = 1
council_two_stage_hash = "blah_blah"
council_forever_hash = "forever_hash"
ics_one_shot_hash = "yes_no_test"
ics_one_shot_index = 1
ics_two_stage_hash = "blah_blah"
ics_forever_hash = "forever_hash"
technical_authority_one_shot_hash = "yes_no_test"
technical_authority_one_shot_index = 1
technical_authority_two_stage_hash = "blah_blah"
technical_authority_forever_hash = "forever_hash"
committee_operators_one_shot_hash = "yes_no_test"
committee_operators_one_shot_index = 1
committee_operators_two_stage_hash = "blah_blah"
committee_operators_forever_hash = "forever_hash"
main_gov_one_shot_hash = "yes_no_test"
main_gov_one_shot_index = 1
main_gov_threshold_hash = "blah_blah"
staging_gov_one_shot_hash = "yes_no_test"
staging_gov_one_shot_index = 1
staging_gov_threshold_hash = "blah_blah"
main_council_update_one_shot_hash = "yes_no_test"
main_council_update_one_shot_index = 1
main_council_update_threshold_hash = "blah_blah"
staging_council_update_one_shot_hash = "yes_no_test"
staging_council_update_one_shot_index = 1
staging_council_update_threshold_hash = "blah_blah"
main_tech_auth_update_one_shot_hash = "yes_no_test"
main_tech_auth_update_one_shot_index = 1
main_tech_auth_update_threshold_hash = "blah_blah"
staging_tech_auth_update_one_shot_hash = "yes_no_test"
staging_tech_auth_update_one_shot_index = 1
staging_tech_auth_update_threshold_hash = "blah_blah"

[config.preview]
reserve_one_shot_hash = "yes_no_test"
reserve_one_shot_index = 1
council_one_shot_hash = "yes_no_test"
council_one_shot_index = 1
ics_one_shot_hash = "yes_no_test"
ics_one_shot_index = 1
technical_authority_one_shot_hash = "yes_no_test"
technical_authority_one_shot_index = 1
committee_operators_one_shot_hash = "yes_no_test"
committee_operators_one_shot_index = 1
main_gov_one_shot_hash = "yes_no_test"
main_gov_one_shot_index = 1
staging_gov_one_shot_hash = "yes_no_test"
staging_gov_one_shot_index = 1
main_council_update_one_shot_hash = "yes_no_test"
main_council_update_one_shot_index = 1
staging_council_update_one_shot_hash = "yes_no_test"
staging_council_update_one_shot_index = 1
main_tech_auth_update_one_shot_hash = "yes_no_test"
main_tech_auth_update_one_shot_index = 1
staging_tech_auth_update_one_shot_hash = "yes_no_test"
staging_tech_auth_update_one_shot_index = 1

[config.preview.cnight_policy]
bytes = "3e8b3d0bda81efcd1ce86d17b7764e55551cec6783f90bbc31069d69"
encoding = "hex"

[config.preview.reserve_two_stage_hash]
bytes = "54545454545454545454545454545454545454545454545454545454"
encoding = "hex"

[config.preview.reserve_forever_hash]
bytes = "12121212121212121212121212121212121212121212121212121212"
encoding = "hex"

[config.preview.council_two_stage_hash]
bytes = "54545454545454545454545454545454545454545454545454545454"
encoding = "hex"

[config.preview.council_forever_hash]
bytes = "45454545454545454545454545454545454545454545454545454545"
encoding = "hex"

[config.preview.ics_two_stage_hash]
bytes = "37373737373737373737373737373737373737373737373737373737"
encoding = "hex"

[config.preview.ics_forever_hash]
bytes = "78787878787878787878787878787878787878787878787878787878"
encoding = "hex"

[config.preview.technical_authority_two_stage_hash]
bytes = "91919191919191919191919191919191919191919191919191919191"
encoding = "hex"

[config.preview.technical_authority_forever_hash]
bytes = "21212121212121212121212121212121212121212121212121212121"
encoding = "hex"

[config.preview.committee_operators_two_stage_hash]
bytes = "63636363636363636363636363636363636363636363636363636363"
encoding = "hex"

[config.preview.committee_operators_forever_hash]
bytes = "84848484848484848484848484848484848484848484848484848484"
encoding = "hex"

[config.preview.main_gov_threshold_hash]
bytes = "95959595959595959595959595959595959595959595959595959595"
encoding = "hex"

[config.preview.staging_gov_threshold_hash]
bytes = "16161616161616161616161616161616161616161616161616161616"
encoding = "hex"

[config.preview.main_council_update_threshold_hash]
bytes = "27272727272727272727272727272727272727272727272727272727"
encoding = "hex"

[config.preview.staging_council_update_threshold_hash]
bytes = "38383838383838383838383838383838383838383838383838383838"
encoding = "hex"

[config.preview.main_tech_auth_update_threshold_hash]
bytes = "49494949494949494949494949494949494949494949494949494949"
encoding = "hex"

[config.preview.staging_tech_auth_update_threshold_hash]
bytes = "50505050505050505050505050505050505050505050505050505050"
encoding = "hex"
