export enum ErrorCode {
  // Session errors
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_ALREADY_EXISTS = 'SESSION_ALREADY_EXISTS',
  SESSION_LIMIT_EXCEEDED = 'SESSION_LIMIT_EXCEEDED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  
  // Wallet errors
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS = 'WALLET_ALREADY_EXISTS',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  
  // Contract errors
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  CONTRACT_COMPILATION_FAILED = 'CONTRACT_COMPILATION_FAILED',
  CONTRACT_DEPLOYMENT_FAILED = 'CONTRACT_DEPLOYMENT_FAILED',
  CONTRACT_EXECUTION_FAILED = 'CONTRACT_EXECUTION_FAILED',
  INVALID_CONTRACT_PARAMS = 'INVALID_CONTRACT_PARAMS',
  
  // Transaction errors
  TRANSACTION_BUILD_FAILED = 'TRANSACTION_BUILD_FAILED',
  TRANSACTION_SIGN_FAILED = 'TRANSACTION_SIGN_FAILED',
  TRANSACTION_SUBMIT_FAILED = 'TRANSACTION_SUBMIT_FAILED',
  INVALID_TRANSACTION = 'INVALID_TRANSACTION',
  
  // Emulator errors
  EMULATOR_INIT_FAILED = 'EMULATOR_INIT_FAILED',
  EMULATOR_CRASHED = 'EMULATOR_CRASHED',
  
  // General errors
  INVALID_REQUEST = 'INVALID_REQUEST',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
}