name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  #v6.0.1
      - uses: aiken-lang/setup-aiken@66c4b83b2ec3d499406f4505b8902ba52b9a4294  #v1.0.3
        with:
          version: v1.1.19
      - run: aiken fmt --check
      - run: aiken check
      - run: aiken build

      - uses: oven-sh/setup-bun@a74d7c3e675a893175d1c9cb22d573f1c6fd0a8d  #v2.0.2
        with:
          bun-version: 1.1.43
      - run: bun install --frozen-lockfile
      - run: bun run fmt:check
      - run: bun run lint
      - run: bun run check
      - run: bun test
